execute if entity @a[scores={llevel=0}] run attribute @a[scores={llevel=0},limit=1] minecraft:generic.luck base set 0.00
execute if entity @a[scores={llevel=1}] run attribute @a[scores={llevel=1},limit=1] minecraft:generic.luck base set 0.25
execute if entity @a[scores={llevel=2}] run attribute @a[scores={llevel=2},limit=1] minecraft:generic.luck base set 0.50
execute if entity @a[scores={llevel=3}] run attribute @a[scores={llevel=3},limit=1] minecraft:generic.luck base set 0.75
execute if entity @a[scores={llevel=4}] run attribute @a[scores={llevel=4},limit=1] minecraft:generic.luck base set 1.00
execute if entity @a[scores={llevel=5}] run attribute @a[scores={llevel=5},limit=1] minecraft:generic.luck base set 1.25
execute if entity @a[scores={llevel=6}] run attribute @a[scores={llevel=6},limit=1] minecraft:generic.luck base set 1.50
execute if entity @a[scores={llevel=7}] run attribute @a[scores={llevel=7},limit=1] minecraft:generic.luck base set 1.75
execute if entity @a[scores={llevel=8}] run attribute @a[scores={llevel=8},limit=1] minecraft:generic.luck base set 2.00
execute if entity @a[scores={llevel=9}] run attribute @a[scores={llevel=9},limit=1] minecraft:generic.luck base set 2.25
execute if entity @a[scores={llevel=10}] run attribute @a[scores={llevel=10},limit=1] minecraft:generic.luck base set 2.50
execute if entity @a[scores={llevel=11}] run attribute @a[scores={llevel=11},limit=1] minecraft:generic.luck base set 2.75
execute if entity @a[scores={llevel=12}] run attribute @a[scores={llevel=12},limit=1] minecraft:generic.luck base set 3.00
execute if entity @a[scores={llevel=13}] run attribute @a[scores={llevel=13},limit=1] minecraft:generic.luck base set 3.25
execute if entity @a[scores={llevel=14}] run attribute @a[scores={llevel=14},limit=1] minecraft:generic.luck base set 3.50
execute if entity @a[scores={llevel=15}] run attribute @a[scores={llevel=15},limit=1] minecraft:generic.luck base set 3.75
execute if entity @a[scores={llevel=16}] run attribute @a[scores={llevel=16},limit=1] minecraft:generic.luck base set 4.00
execute if entity @a[scores={llevel=17}] run attribute @a[scores={llevel=17},limit=1] minecraft:generic.luck base set 4.25
execute if entity @a[scores={llevel=18}] run attribute @a[scores={llevel=18},limit=1] minecraft:generic.luck base set 4.50
execute if entity @a[scores={llevel=19}] run attribute @a[scores={llevel=19},limit=1] minecraft:generic.luck base set 4.75
execute if entity @a[scores={llevel=20}] run attribute @a[scores={llevel=20},limit=1] minecraft:generic.luck base set 5.00