execute if entity @a[scores={mlevel=0}] run attribute @a[scores={mlevel=0},limit=1] minecraft:generic.attack_speed base set 3.8
execute if entity @a[scores={mlevel=0}] run attribute @a[scores={mlevel=0},limit=1] minecraft:generic.attack_damage base set -2
execute if entity @a[scores={meleedamage=1000..,mlevel=0}] run function serverfunctions:melee_levels/melee_lvl_0.mcfunction
execute if entity @a[scores={meleedamage=2090..,mlevel=1}] run function serverfunctions:melee_levels/melee_lvl_1.mcfunction
execute if entity @a[scores={meleedamage=3278..,mlevel=2}] run function serverfunctions:melee_levels/melee_lvl_2.mcfunction
execute if entity @a[scores={meleedamage=4573..,mlevel=3}] run function serverfunctions:melee_levels/melee_lvl_3.mcfunction
execute if entity @a[scores={meleedamage=5984..,mlevel=4}] run function serverfunctions:melee_levels/melee_lvl_4.mcfunction
execute if entity @a[scores={meleedamage=7522..,mlevel=5}] run function serverfunctions:melee_levels/melee_lvl_5.mcfunction
execute if entity @a[scores={meleedamage=9199..,mlevel=6}] run function serverfunctions:melee_levels/melee_lvl_6.mcfunction
execute if entity @a[scores={meleedamage=11027..,mlevel=7}] run function serverfunctions:melee_levels/melee_lvl_7.mcfunction
execute if entity @a[scores={meleedamage=13019..,mlevel=8}] run function serverfunctions:melee_levels/melee_lvl_8.mcfunction
execute if entity @a[scores={meleedamage=15190..,mlevel=9}] run function serverfunctions:melee_levels/melee_lvl_9.mcfunction
execute if entity @a[scores={meleedamage=17557..,mlevel=10}] run function serverfunctions:melee_levels/melee_lvl_10.mcfunction
execute if entity @a[scores={meleedamage=20137..,mlevel=11}] run function serverfunctions:melee_levels/melee_lvl_11.mcfunction
execute if entity @a[scores={meleedamage=22949..,mlevel=12}] run function serverfunctions:melee_levels/melee_lvl_12.mcfunction
execute if entity @a[scores={meleedamage=26014..,mlevel=13}] run function serverfunctions:melee_levels/melee_lvl_13.mcfunction
execute if entity @a[scores={meleedamage=29355..,mlevel=14}] run function serverfunctions:melee_levels/melee_lvl_14.mcfunction
execute if entity @a[scores={meleedamage=32997..,mlevel=15}] run function serverfunctions:melee_levels/melee_lvl_15.mcfunction
execute if entity @a[scores={meleedamage=36967..,mlevel=16}] run function serverfunctions:melee_levels/melee_lvl_16.mcfunction
execute if entity @a[scores={meleedamage=41294..,mlevel=17}] run function serverfunctions:melee_levels/melee_lvl_17.mcfunction
execute if entity @a[scores={meleedamage=46011..,mlevel=18}] run function serverfunctions:melee_levels/melee_lvl_18.mcfunction
execute if entity @a[scores={meleedamage=51152..,mlevel=19}] run function serverfunctions:melee_levels/melee_lvl_19.mcfunction
execute if entity @a[scores={meleedamage=56756..,mlevel=20}] run function serverfunctions:melee_levels/melee_lvl_20.mcfunction
execute if entity @a[scores={meleedamage=62864..,mlevel=21}] run function serverfunctions:melee_levels/melee_lvl_21.mcfunction
execute if entity @a[scores={meleedamage=69522..,mlevel=22}] run function serverfunctions:melee_levels/melee_lvl_22.mcfunction
execute if entity @a[scores={meleedamage=76779..,mlevel=23}] run function serverfunctions:melee_levels/melee_lvl_23.mcfunction
execute if entity @a[scores={meleedamage=84690..,mlevel=24}] run function serverfunctions:melee_levels/melee_lvl_24.mcfunction
execute if entity @a[scores={meleedamage=93313..,mlevel=25}] run function serverfunctions:melee_levels/melee_lvl_25.mcfunction
execute if entity @a[scores={meleedamage=102712..,mlevel=26}] run function serverfunctions:melee_levels/melee_lvl_26.mcfunction
execute if entity @a[scores={meleedamage=112957..,mlevel=27}] run function serverfunctions:melee_levels/melee_lvl_27.mcfunction
execute if entity @a[scores={meleedamage=124124..,mlevel=28}] run function serverfunctions:melee_levels/melee_lvl_28.mcfunction
execute if entity @a[scores={meleedamage=136296..,mlevel=29}] run function serverfunctions:melee_levels/melee_lvl_29.mcfunction
execute if entity @a[scores={meleedamage=149563..,mlevel=30}] run function serverfunctions:melee_levels/melee_lvl_30.mcfunction
execute if entity @a[scores={meleedamage=164024..,mlevel=31}] run function serverfunctions:melee_levels/melee_lvl_31.mcfunction
execute if entity @a[scores={meleedamage=179787..,mlevel=32}] run function serverfunctions:melee_levels/melee_lvl_32.mcfunction
execute if entity @a[scores={meleedamage=196969..,mlevel=33}] run function serverfunctions:melee_levels/melee_lvl_33.mcfunction
execute if entity @a[scores={meleedamage=215697..,mlevel=34}] run function serverfunctions:melee_levels/melee_lvl_34.mcfunction
execute if entity @a[scores={meleedamage=236110..,mlevel=35}] run function serverfunctions:melee_levels/melee_lvl_35.mcfunction
execute if entity @a[scores={meleedamage=258361..,mlevel=36}] run function serverfunctions:melee_levels/melee_lvl_36.mcfunction
execute if entity @a[scores={meleedamage=282614..,mlevel=37}] run function serverfunctions:melee_levels/melee_lvl_37.mcfunction
execute if entity @a[scores={meleedamage=309050..,mlevel=38}] run function serverfunctions:melee_levels/melee_lvl_38.mcfunction
execute if entity @a[scores={meleedamage=337865..,mlevel=39}] run function serverfunctions:melee_levels/melee_lvl_39.mcfunction
execute if entity @a[scores={meleedamage=369274..,mlevel=40}] run function serverfunctions:melee_levels/melee_lvl_40.mcfunction
execute if entity @a[scores={meleedamage=403510..,mlevel=41}] run function serverfunctions:melee_levels/melee_lvl_41.mcfunction
execute if entity @a[scores={meleedamage=440827..,mlevel=42}] run function serverfunctions:melee_levels/melee_lvl_42.mcfunction
execute if entity @a[scores={meleedamage=481503..,mlevel=43}] run function serverfunctions:melee_levels/melee_lvl_43.mcfunction
execute if entity @a[scores={meleedamage=525839..,mlevel=44}] run function serverfunctions:melee_levels/melee_lvl_44.mcfunction
execute if entity @a[scores={meleedamage=574166..,mlevel=45}] run function serverfunctions:melee_levels/melee_lvl_45.mcfunction
execute if entity @a[scores={meleedamage=626842..,mlevel=46}] run function serverfunctions:melee_levels/melee_lvl_46.mcfunction
execute if entity @a[scores={meleedamage=684259..,mlevel=47}] run function serverfunctions:melee_levels/melee_lvl_47.mcfunction
execute if entity @a[scores={meleedamage=746844..,mlevel=48}] run function serverfunctions:melee_levels/melee_lvl_48.mcfunction
execute if entity @a[scores={meleedamage=815061..,mlevel=49}] run function serverfunctions:melee_levels/melee_lvl_49.mcfunction