execute if entity @a[scores={sprint=20000..,slevel=0}] run tellraw @a[scores={sprint=20000..,slevel=0}] ["",{"text":"Sprinting Level Up!","bold":true,"color":"gold"},{"text":" Level 0","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"Level 1","bold":true,"color":"white"},{"text":"\nWalk Speed","bold":true,"color":"yellow"},{"text":" 0.0%","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"0.5%","bold":true,"color":"white"}]
execute if entity @a[scores={sprint=20000..,slevel=0}] run attribute @a[scores={sprint=20000..,slevel=0},limit=1] minecraft:generic.movement_speed base set 0.1005
execute if entity @a[scores={sprint=20000..,slevel=0}] run execute at @a[scores={sprint=20000..,slevel=0}] run playsound minecraft:entity.player.levelup master @a ~ ~ ~ 1 1.2
execute at @a[scores={sprint=20000..,slevel=0}] run tellraw @a[distance=.01..40] {"text":"","color":"gold","extra":[{"selector":"@a[scores={sprint=20000..,slevel=0}]"},{"text":" is now Sprinting Level 1"}]}
execute if entity @a[scores={sprint=20000..,slevel=0}] run scoreboard players set @a[scores={sprint=20000..,slevel=0}] slevel 1
execute if entity @a[scores={sprint=42400..,slevel=1}] run tellraw @a[scores={sprint=42400..,slevel=1}] ["",{"text":"Sprinting Level Up!","bold":true,"color":"gold"},{"text":" Level 1","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"Level 2","bold":true,"color":"white"},{"text":"\nWalk Speed","bold":true,"color":"yellow"},{"text":" 0.5%","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"1.0%","bold":true,"color":"white"}]
execute if entity @a[scores={sprint=42400..,slevel=1}] run attribute @a[scores={sprint=42400..,slevel=1},limit=1] minecraft:generic.movement_speed base set 0.1010
execute if entity @a[scores={sprint=42400..,slevel=1}] run execute at @a[scores={sprint=42400..,slevel=1}] run playsound minecraft:entity.player.levelup master @a ~ ~ ~ 1 1.2
execute at @a[scores={sprint=42400..,slevel=1}] run tellraw @a[distance=.01..40] {"text":"","color":"gold","extra":[{"selector":"@a[scores={sprint=42400..,slevel=1}]"},{"text":" is now Sprinting Level 2"}]}
execute if entity @a[scores={sprint=42400..,slevel=1}] run scoreboard players set @a[scores={sprint=42400..,slevel=1}] slevel 2
execute if entity @a[scores={sprint=67488..,slevel=2}] run tellraw @a[scores={sprint=67488..,slevel=2}] ["",{"text":"Sprinting Level Up!","bold":true,"color":"gold"},{"text":" Level 2","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"Level 3","bold":true,"color":"white"},{"text":"\nWalk Speed","bold":true,"color":"yellow"},{"text":" 1.0%","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"1.5%","bold":true,"color":"white"}]
execute if entity @a[scores={sprint=67488..,slevel=2}] run attribute @a[scores={sprint=67488..,slevel=2},limit=1] minecraft:generic.movement_speed base set 0.1015
execute if entity @a[scores={sprint=67488..,slevel=2}] run execute at @a[scores={sprint=67488..,slevel=2}] run playsound minecraft:entity.player.levelup master @a ~ ~ ~ 1 1.2
execute at @a[scores={sprint=67488..,slevel=2}] run tellraw @a[distance=.01..40] {"text":"","color":"gold","extra":[{"selector":"@a[scores={sprint=67488..,slevel=2}]"},{"text":" is now Sprinting Level 3"}]}
execute if entity @a[scores={sprint=67488..,slevel=2}] run scoreboard players set @a[scores={sprint=67488..,slevel=2}] slevel 3
execute if entity @a[scores={sprint=95586..,slevel=3}] run tellraw @a[scores={sprint=95586..,slevel=3}] ["",{"text":"Sprinting Level Up!","bold":true,"color":"gold"},{"text":" Level 3","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"Level 4","bold":true,"color":"white"},{"text":"\nWalk Speed","bold":true,"color":"yellow"},{"text":" 1.5%","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"2.0%","bold":true,"color":"white"}]
execute if entity @a[scores={sprint=95586..,slevel=3}] run attribute @a[scores={sprint=95586..,slevel=3},limit=1] minecraft:generic.movement_speed base set 0.1020
execute if entity @a[scores={sprint=95586..,slevel=3}] run execute at @a[scores={sprint=95586..,slevel=3}] run playsound minecraft:entity.player.levelup master @a ~ ~ ~ 1 1.2
execute at @a[scores={sprint=95586..,slevel=3}] run tellraw @a[distance=.01..40] {"text":"","color":"gold","extra":[{"selector":"@a[scores={sprint=95586..,slevel=3}]"},{"text":" is now Sprinting Level 4"}]}
execute if entity @a[scores={sprint=95586..,slevel=3}] run scoreboard players set @a[scores={sprint=95586..,slevel=3}] slevel 4
execute if entity @a[scores={sprint=127056..,slevel=4}] run tellraw @a[scores={sprint=127056..,slevel=4}] ["",{"text":"Sprinting Level Up!","bold":true,"color":"gold"},{"text":" Level 4","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"Level 5","bold":true,"color":"white"},{"text":"\nWalk Speed","bold":true,"color":"yellow"},{"text":" 2.0%","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"2.5%","bold":true,"color":"white"}]
execute if entity @a[scores={sprint=127056..,slevel=4}] run attribute @a[scores={sprint=127056..,slevel=4},limit=1] minecraft:generic.movement_speed base set 0.1025
execute if entity @a[scores={sprint=127056..,slevel=4}] run execute at @a[scores={sprint=127056..,slevel=4}] run playsound minecraft:entity.player.levelup master @a ~ ~ ~ 1 1.2
execute at @a[scores={sprint=127056..,slevel=4}] run tellraw @a[distance=.01..40] {"text":"","color":"gold","extra":[{"selector":"@a[scores={sprint=127056..,slevel=4}]"},{"text":" is now Sprinting Level 5"}]}
execute if entity @a[scores={sprint=127056..,slevel=4}] run tellraw @a[scores={sprint=127056..,slevel=4}] ["",{"text":"Luck Level Up!","bold":true,"color":"blue"}]
execute if entity @a[scores={sprint=127056..,slevel=4}] run scoreboard players add @a[scores={sprint=127056..,slevel=4}] llevel 1
execute if entity @a[scores={sprint=127056..,slevel=4}] run scoreboard players set @a[scores={sprint=127056..,slevel=4}] slevel 5
execute if entity @a[scores={sprint=162302..,slevel=5}] run tellraw @a[scores={sprint=162302..,slevel=5}] ["",{"text":"Sprinting Level Up!","bold":true,"color":"gold"},{"text":" Level 5","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"Level 6","bold":true,"color":"white"},{"text":"\nWalk Speed","bold":true,"color":"yellow"},{"text":" 2.5%","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"3.0%","bold":true,"color":"white"}]
execute if entity @a[scores={sprint=162302..,slevel=5}] run attribute @a[scores={sprint=162302..,slevel=5},limit=1] minecraft:generic.movement_speed base set 0.1030
execute if entity @a[scores={sprint=162302..,slevel=5}] run execute at @a[scores={sprint=162302..,slevel=5}] run playsound minecraft:entity.player.levelup master @a ~ ~ ~ 1 1.2
execute at @a[scores={sprint=162302..,slevel=5}] run tellraw @a[distance=.01..40] {"text":"","color":"gold","extra":[{"selector":"@a[scores={sprint=162302..,slevel=5}]"},{"text":" is now Sprinting Level 6"}]}
execute if entity @a[scores={sprint=162302..,slevel=5}] run scoreboard players set @a[scores={sprint=162302..,slevel=5}] slevel 6
execute if entity @a[scores={sprint=201778..,slevel=6}] run tellraw @a[scores={sprint=201778..,slevel=6}] ["",{"text":"Sprinting Level Up!","bold":true,"color":"gold"},{"text":" Level 6","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"Level 7","bold":true,"color":"white"},{"text":"\nWalk Speed","bold":true,"color":"yellow"},{"text":" 3.0%","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"3.5%","bold":true,"color":"white"}]
execute if entity @a[scores={sprint=201778..,slevel=6}] run attribute @a[scores={sprint=201778..,slevel=6},limit=1] minecraft:generic.movement_speed base set 0.1035
execute if entity @a[scores={sprint=201778..,slevel=6}] run execute at @a[scores={sprint=201778..,slevel=6}] run playsound minecraft:entity.player.levelup master @a ~ ~ ~ 1 1.2
execute at @a[scores={sprint=201778..,slevel=6}] run tellraw @a[distance=.01..40] {"text":"","color":"gold","extra":[{"selector":"@a[scores={sprint=201778..,slevel=6}]"},{"text":" is now Sprinting Level 7"}]}
execute if entity @a[scores={sprint=201778..,slevel=6}] run scoreboard players set @a[scores={sprint=201778..,slevel=6}] slevel 7
execute if entity @a[scores={sprint=245991..,slevel=7}] run tellraw @a[scores={sprint=245991..,slevel=7}] ["",{"text":"Sprinting Level Up!","bold":true,"color":"gold"},{"text":" Level 7","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"Level 8","bold":true,"color":"white"},{"text":"\nWalk Speed","bold":true,"color":"yellow"},{"text":" 3.5%","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"4.0%","bold":true,"color":"white"}]
execute if entity @a[scores={sprint=245991..,slevel=7}] run attribute @a[scores={sprint=245991..,slevel=7},limit=1] minecraft:generic.movement_speed base set 0.1040
execute if entity @a[scores={sprint=245991..,slevel=7}] run execute at @a[scores={sprint=245991..,slevel=7}] run playsound minecraft:entity.player.levelup master @a ~ ~ ~ 1 1.2
execute at @a[scores={sprint=245991..,slevel=7}] run tellraw @a[distance=.01..40] {"text":"","color":"gold","extra":[{"selector":"@a[scores={sprint=245991..,slevel=7}]"},{"text":" is now Sprinting Level 8"}]}
execute if entity @a[scores={sprint=245991..,slevel=7}] run scoreboard players set @a[scores={sprint=245991..,slevel=7}] slevel 8
execute if entity @a[scores={sprint=295510..,slevel=8}] run tellraw @a[scores={sprint=295510..,slevel=8}] ["",{"text":"Sprinting Level Up!","bold":true,"color":"gold"},{"text":" Level 8","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"Level 9","bold":true,"color":"white"},{"text":"\nWalk Speed","bold":true,"color":"yellow"},{"text":" 4.0%","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"4.5%","bold":true,"color":"white"}]
execute if entity @a[scores={sprint=295510..,slevel=8}] run attribute @a[scores={sprint=295510..,slevel=8},limit=1] minecraft:generic.movement_speed base set 0.1045
execute if entity @a[scores={sprint=295510..,slevel=8}] run execute at @a[scores={sprint=295510..,slevel=8}] run playsound minecraft:entity.player.levelup master @a ~ ~ ~ 1 1.2
execute at @a[scores={sprint=295510..,slevel=8}] run tellraw @a[distance=.01..40] {"text":"","color":"gold","extra":[{"selector":"@a[scores={sprint=295510..,slevel=8}]"},{"text":" is now Sprinting Level 9"}]}
execute if entity @a[scores={sprint=295510..,slevel=8}] run scoreboard players set @a[scores={sprint=295510..,slevel=8}] slevel 9
execute if entity @a[scores={sprint=350971..,slevel=9}] run tellraw @a[scores={sprint=350971..,slevel=9}] ["",{"text":"Sprinting Level Up!","bold":true,"color":"gold"},{"text":" Level 9","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"Level 10","bold":true,"color":"white"},{"text":"\nWalk Speed","bold":true,"color":"yellow"},{"text":" 4.5%","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"5.0%","bold":true,"color":"white"}]
execute if entity @a[scores={sprint=350971..,slevel=9}] run attribute @a[scores={sprint=350971..,slevel=9},limit=1] minecraft:generic.movement_speed base set 0.1050
execute if entity @a[scores={sprint=350971..,slevel=9}] run execute at @a[scores={sprint=350971..,slevel=9}] run playsound minecraft:entity.player.levelup master @a ~ ~ ~ 1 1.2
execute at @a[scores={sprint=350971..,slevel=9}] run tellraw @a[distance=.01..40] {"text":"","color":"gold","extra":[{"selector":"@a[scores={sprint=350971..,slevel=9}]"},{"text":" is now Sprinting Level 10"}]}
execute if entity @a[scores={sprint=350971..,slevel=9}] run tellraw @a[scores={sprint=350971..,slevel=9}] ["",{"text":"Luck Level Up!","bold":true,"color":"blue"}]
execute if entity @a[scores={sprint=350971..,slevel=9}] run scoreboard players add @a[scores={sprint=350971..,slevel=9}] llevel 1
execute if entity @a[scores={sprint=350971..,slevel=9}] run scoreboard players set @a[scores={sprint=350971..,slevel=9}] slevel 10
execute if entity @a[scores={sprint=413087..,slevel=10}] run tellraw @a[scores={sprint=413087..,slevel=10}] ["",{"text":"Sprinting Level Up!","bold":true,"color":"gold"},{"text":" Level 10","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"Level 11","bold":true,"color":"white"},{"text":"\nWalk Speed","bold":true,"color":"yellow"},{"text":" 5.0%","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"5.5%","bold":true,"color":"white"}]
execute if entity @a[scores={sprint=413087..,slevel=10}] run attribute @a[scores={sprint=413087..,slevel=10},limit=1] minecraft:generic.movement_speed base set 0.1055
execute if entity @a[scores={sprint=413087..,slevel=10}] run execute at @a[scores={sprint=413087..,slevel=10}] run playsound minecraft:entity.player.levelup master @a ~ ~ ~ 1 1.2
execute at @a[scores={sprint=413087..,slevel=10}] run tellraw @a[distance=.01..40] {"text":"","color":"gold","extra":[{"selector":"@a[scores={sprint=413087..,slevel=10}]"},{"text":" is now Sprinting Level 11"}]}
execute if entity @a[scores={sprint=413087..,slevel=10}] run scoreboard players set @a[scores={sprint=413087..,slevel=10}] slevel 11
execute if entity @a[scores={sprint=482657..,slevel=11}] run tellraw @a[scores={sprint=482657..,slevel=11}] ["",{"text":"Sprinting Level Up!","bold":true,"color":"gold"},{"text":" Level 11","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"Level 12","bold":true,"color":"white"},{"text":"\nWalk Speed","bold":true,"color":"yellow"},{"text":" 5.5%","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"6.0%","bold":true,"color":"white"}]
execute if entity @a[scores={sprint=482657..,slevel=11}] run attribute @a[scores={sprint=482657..,slevel=11},limit=1] minecraft:generic.movement_speed base set 0.1060
execute if entity @a[scores={sprint=482657..,slevel=11}] run execute at @a[scores={sprint=482657..,slevel=11}] run playsound minecraft:entity.player.levelup master @a ~ ~ ~ 1 1.2
execute at @a[scores={sprint=482657..,slevel=11}] run tellraw @a[distance=.01..40] {"text":"","color":"gold","extra":[{"selector":"@a[scores={sprint=482657..,slevel=11}]"},{"text":" is now Sprinting Level 12"}]}
execute if entity @a[scores={sprint=482657..,slevel=11}] run scoreboard players set @a[scores={sprint=482657..,slevel=11}] slevel 12
execute if entity @a[scores={sprint=560576..,slevel=12}] run tellraw @a[scores={sprint=560576..,slevel=12}] ["",{"text":"Sprinting Level Up!","bold":true,"color":"gold"},{"text":" Level 12","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"Level 13","bold":true,"color":"white"},{"text":"\nWalk Speed","bold":true,"color":"yellow"},{"text":" 6.0%","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"6.5%","bold":true,"color":"white"}]
execute if entity @a[scores={sprint=560576..,slevel=12}] run attribute @a[scores={sprint=560576..,slevel=12},limit=1] minecraft:generic.movement_speed base set 0.1065
execute if entity @a[scores={sprint=560576..,slevel=12}] run execute at @a[scores={sprint=560576..,slevel=12}] run playsound minecraft:entity.player.levelup master @a ~ ~ ~ 1 1.2
execute at @a[scores={sprint=560576..,slevel=12}] run tellraw @a[distance=.01..40] {"text":"","color":"gold","extra":[{"selector":"@a[scores={sprint=560576..,slevel=12}]"},{"text":" is now Sprinting Level 13"}]}
execute if entity @a[scores={sprint=560576..,slevel=12}] run scoreboard players set @a[scores={sprint=560576..,slevel=12}] slevel 13
execute if entity @a[scores={sprint=647845..,slevel=13}] run tellraw @a[scores={sprint=647845..,slevel=13}] ["",{"text":"Sprinting Level Up!","bold":true,"color":"gold"},{"text":" Level 13","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"Level 14","bold":true,"color":"white"},{"text":"\nWalk Speed","bold":true,"color":"yellow"},{"text":" 6.5%","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"7.0%","bold":true,"color":"white"}]
execute if entity @a[scores={sprint=647845..,slevel=13}] run attribute @a[scores={sprint=647845..,slevel=13},limit=1] minecraft:generic.movement_speed base set 0.1070
execute if entity @a[scores={sprint=647845..,slevel=13}] run execute at @a[scores={sprint=647845..,slevel=13}] run playsound minecraft:entity.player.levelup master @a ~ ~ ~ 1 1.2
execute at @a[scores={sprint=647845..,slevel=13}] run tellraw @a[distance=.01..40] {"text":"","color":"gold","extra":[{"selector":"@a[scores={sprint=647845..,slevel=13}]"},{"text":" is now Sprinting Level 14"}]}
execute if entity @a[scores={sprint=647845..,slevel=13}] run scoreboard players set @a[scores={sprint=647845..,slevel=13}] slevel 14
execute if entity @a[scores={sprint=745587..,slevel=14}] run tellraw @a[scores={sprint=745587..,slevel=14}] ["",{"text":"Sprinting Level Up!","bold":true,"color":"gold"},{"text":" Level 14","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"Level 15","bold":true,"color":"white"},{"text":"\nWalk Speed","bold":true,"color":"yellow"},{"text":" 7.0%","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"7.5%","bold":true,"color":"white"}]
execute if entity @a[scores={sprint=745587..,slevel=14}] run attribute @a[scores={sprint=745587..,slevel=14},limit=1] minecraft:generic.movement_speed base set 0.1075
execute if entity @a[scores={sprint=745587..,slevel=14}] run execute at @a[scores={sprint=745587..,slevel=14}] run playsound minecraft:entity.player.levelup master @a ~ ~ ~ 1 1.2
execute at @a[scores={sprint=745587..,slevel=14}] run tellraw @a[distance=.01..40] {"text":"","color":"gold","extra":[{"selector":"@a[scores={sprint=745587..,slevel=14}]"},{"text":" is now Sprinting Level 15"}]}
execute if entity @a[scores={sprint=745587..,slevel=14}] run tellraw @a[scores={sprint=745587..,slevel=14}] ["",{"text":"Luck Level Up!","bold":true,"color":"blue"}]
execute if entity @a[scores={sprint=745587..,slevel=14}] run scoreboard players add @a[scores={sprint=745587..,slevel=14}] llevel 1
execute if entity @a[scores={sprint=745587..,slevel=14}] run scoreboard players set @a[scores={sprint=745587..,slevel=14}] slevel 15
execute if entity @a[scores={sprint=855058..,slevel=15}] run tellraw @a[scores={sprint=855058..,slevel=15}] ["",{"text":"Sprinting Level Up!","bold":true,"color":"gold"},{"text":" Level 15","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"Level 16","bold":true,"color":"white"},{"text":"\nWalk Speed","bold":true,"color":"yellow"},{"text":" 7.5%","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"8.0%","bold":true,"color":"white"}]
execute if entity @a[scores={sprint=855058..,slevel=15}] run attribute @a[scores={sprint=855058..,slevel=15},limit=1] minecraft:generic.movement_speed base set 0.1080
execute if entity @a[scores={sprint=855058..,slevel=15}] run execute at @a[scores={sprint=855058..,slevel=15}] run playsound minecraft:entity.player.levelup master @a ~ ~ ~ 1 1.2
execute at @a[scores={sprint=855058..,slevel=15}] run tellraw @a[distance=.01..40] {"text":"","color":"gold","extra":[{"selector":"@a[scores={sprint=855058..,slevel=15}]"},{"text":" is now Sprinting Level 16"}]}
execute if entity @a[scores={sprint=855058..,slevel=15}] run scoreboard players set @a[scores={sprint=855058..,slevel=15}] slevel 16
execute if entity @a[scores={sprint=977665..,slevel=16}] run tellraw @a[scores={sprint=977665..,slevel=16}] ["",{"text":"Sprinting Level Up!","bold":true,"color":"gold"},{"text":" Level 16","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"Level 17","bold":true,"color":"white"},{"text":"\nWalk Speed","bold":true,"color":"yellow"},{"text":" 8.0%","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"8.5%","bold":true,"color":"white"}]
execute if entity @a[scores={sprint=977665..,slevel=16}] run attribute @a[scores={sprint=977665..,slevel=16},limit=1] minecraft:generic.movement_speed base set 0.1085
execute if entity @a[scores={sprint=977665..,slevel=16}] run execute at @a[scores={sprint=977665..,slevel=16}] run playsound minecraft:entity.player.levelup master @a ~ ~ ~ 1 1.2
execute at @a[scores={sprint=977665..,slevel=16}] run tellraw @a[distance=.01..40] {"text":"","color":"gold","extra":[{"selector":"@a[scores={sprint=977665..,slevel=16}]"},{"text":" is now Sprinting Level 17"}]}
execute if entity @a[scores={sprint=977665..,slevel=16}] run scoreboard players set @a[scores={sprint=977665..,slevel=16}] slevel 17
execute if entity @a[scores={sprint=1114985..,slevel=17}] run tellraw @a[scores={sprint=1114985..,slevel=17}] ["",{"text":"Sprinting Level Up!","bold":true,"color":"gold"},{"text":" Level 17","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"Level 18","bold":true,"color":"white"},{"text":"\nWalk Speed","bold":true,"color":"yellow"},{"text":" 8.5%","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"9.0%","bold":true,"color":"white"}]
execute if entity @a[scores={sprint=1114985..,slevel=17}] run attribute @a[scores={sprint=1114985..,slevel=17},limit=1] minecraft:generic.movement_speed base set 0.1090
execute if entity @a[scores={sprint=1114985..,slevel=17}] run execute at @a[scores={sprint=1114985..,slevel=17}] run playsound minecraft:entity.player.levelup master @a ~ ~ ~ 1 1.2
execute at @a[scores={sprint=1114985..,slevel=17}] run tellraw @a[distance=.01..40] {"text":"","color":"gold","extra":[{"selector":"@a[scores={sprint=1114985..,slevel=17}]"},{"text":" is now Sprinting Level 18"}]}
execute if entity @a[scores={sprint=1114985..,slevel=17}] run scoreboard players set @a[scores={sprint=1114985..,slevel=17}] slevel 18
execute if entity @a[scores={sprint=1268784..,slevel=18}] run tellraw @a[scores={sprint=1268784..,slevel=18}] ["",{"text":"Sprinting Level Up!","bold":true,"color":"gold"},{"text":" Level 18","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"Level 19","bold":true,"color":"white"},{"text":"\nWalk Speed","bold":true,"color":"yellow"},{"text":" 9.0%","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"9.5%","bold":true,"color":"white"}]
execute if entity @a[scores={sprint=1268784..,slevel=18}] run attribute @a[scores={sprint=1268784..,slevel=18},limit=1] minecraft:generic.movement_speed base set 0.1095
execute if entity @a[scores={sprint=1268784..,slevel=18}] run execute at @a[scores={sprint=1268784..,slevel=18}] run playsound minecraft:entity.player.levelup master @a ~ ~ ~ 1 1.2
execute at @a[scores={sprint=1268784..,slevel=18}] run tellraw @a[distance=.01..40] {"text":"","color":"gold","extra":[{"selector":"@a[scores={sprint=1268784..,slevel=18}]"},{"text":" is now Sprinting Level 19"}]}
execute if entity @a[scores={sprint=1268784..,slevel=18}] run scoreboard players set @a[scores={sprint=1268784..,slevel=18}] slevel 19
execute if entity @a[scores={sprint=1441039..,slevel=19}] run tellraw @a[scores={sprint=1441039..,slevel=19}] ["",{"text":"Sprinting Level Up!","bold":true,"color":"gold"},{"text":" Level 19","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"Level 20","bold":true,"color":"white"},{"text":"\nWalk Speed","bold":true,"color":"yellow"},{"text":" 9.5%","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"10.0%","bold":true,"color":"white"}]
execute if entity @a[scores={sprint=1441039..,slevel=19}] run attribute @a[scores={sprint=1441039..,slevel=19},limit=1] minecraft:generic.movement_speed base set 0.1100
execute if entity @a[scores={sprint=1441039..,slevel=19}] run execute at @a[scores={sprint=1441039..,slevel=19}] run playsound minecraft:entity.player.levelup master @a ~ ~ ~ 1 1.2
execute at @a[scores={sprint=1441039..,slevel=19}] run tellraw @a[distance=.01..40] {"text":"","color":"gold","extra":[{"selector":"@a[scores={sprint=1441039..,slevel=19}]"},{"text":" is now Sprinting Level 20"}]}
execute if entity @a[scores={sprint=1441039..,slevel=19}] run tellraw @a[scores={sprint=1441039..,slevel=19}] ["",{"text":"Luck Level Up!","bold":true,"color":"blue"}]
execute if entity @a[scores={sprint=1441039..,slevel=19}] run scoreboard players add @a[scores={sprint=1441039..,slevel=19}] llevel 1
execute if entity @a[scores={sprint=1441039..,slevel=19}] run scoreboard players set @a[scores={sprint=1441039..,slevel=19}] slevel 20
execute if entity @a[scores={sprint=1633964..,slevel=20}] run tellraw @a[scores={sprint=1633964..,slevel=20}] ["",{"text":"Sprinting Level Up!","bold":true,"color":"gold"},{"text":" Level 20","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"Level 21","bold":true,"color":"white"},{"text":"\nWalk Speed","bold":true,"color":"yellow"},{"text":" 10.0%","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"10.5%","bold":true,"color":"white"}]
execute if entity @a[scores={sprint=1633964..,slevel=20}] run attribute @a[scores={sprint=1633964..,slevel=20},limit=1] minecraft:generic.movement_speed base set 0.1105
execute if entity @a[scores={sprint=1633964..,slevel=20}] run execute at @a[scores={sprint=1633964..,slevel=20}] run playsound minecraft:entity.player.levelup master @a ~ ~ ~ 1 1.2
execute at @a[scores={sprint=1633964..,slevel=20}] run tellraw @a[distance=.01..40] {"text":"","color":"gold","extra":[{"selector":"@a[scores={sprint=1633964..,slevel=20}]"},{"text":" is now Sprinting Level 21"}]}
execute if entity @a[scores={sprint=1633964..,slevel=20}] run scoreboard players set @a[scores={sprint=1633964..,slevel=20}] slevel 21
execute if entity @a[scores={sprint=1850040..,slevel=21}] run tellraw @a[scores={sprint=1850040..,slevel=21}] ["",{"text":"Sprinting Level Up!","bold":true,"color":"gold"},{"text":" Level 21","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"Level 22","bold":true,"color":"white"},{"text":"\nWalk Speed","bold":true,"color":"yellow"},{"text":" 10.5%","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"11.0%","bold":true,"color":"white"}]
execute if entity @a[scores={sprint=1850040..,slevel=21}] run attribute @a[scores={sprint=1850040..,slevel=21},limit=1] minecraft:generic.movement_speed base set 0.1110
execute if entity @a[scores={sprint=1850040..,slevel=21}] run execute at @a[scores={sprint=1850040..,slevel=21}] run playsound minecraft:entity.player.levelup master @a ~ ~ ~ 1 1.2
execute at @a[scores={sprint=1850040..,slevel=21}] run tellraw @a[distance=.01..40] {"text":"","color":"gold","extra":[{"selector":"@a[scores={sprint=1850040..,slevel=21}]"},{"text":" is now Sprinting Level 22"}]}
execute if entity @a[scores={sprint=1850040..,slevel=21}] run scoreboard players set @a[scores={sprint=1850040..,slevel=21}] slevel 22
execute if entity @a[scores={sprint=2092046..,slevel=22}] run tellraw @a[scores={sprint=2092046..,slevel=22}] ["",{"text":"Sprinting Level Up!","bold":true,"color":"gold"},{"text":" Level 22","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"Level 23","bold":true,"color":"white"},{"text":"\nWalk Speed","bold":true,"color":"yellow"},{"text":" 11.0%","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"11.5%","bold":true,"color":"white"}]
execute if entity @a[scores={sprint=2092046..,slevel=22}] run attribute @a[scores={sprint=2092046..,slevel=22},limit=1] minecraft:generic.movement_speed base set 0.1115
execute if entity @a[scores={sprint=2092046..,slevel=22}] run execute at @a[scores={sprint=2092046..,slevel=22}] run playsound minecraft:entity.player.levelup master @a ~ ~ ~ 1 1.2
execute at @a[scores={sprint=2092046..,slevel=22}] run tellraw @a[distance=.01..40] {"text":"","color":"gold","extra":[{"selector":"@a[scores={sprint=2092046..,slevel=22}]"},{"text":" is now Sprinting Level 23"}]}
execute if entity @a[scores={sprint=2092046..,slevel=22}] run scoreboard players set @a[scores={sprint=2092046..,slevel=22}] slevel 23
execute if entity @a[scores={sprint=2363092..,slevel=23}] run tellraw @a[scores={sprint=2363092..,slevel=23}] ["",{"text":"Sprinting Level Up!","bold":true,"color":"gold"},{"text":" Level 23","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"Level 24","bold":true,"color":"white"},{"text":"\nWalk Speed","bold":true,"color":"yellow"},{"text":" 11.5%","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"12.0%","bold":true,"color":"white"}]
execute if entity @a[scores={sprint=2363092..,slevel=23}] run attribute @a[scores={sprint=2363092..,slevel=23},limit=1] minecraft:generic.movement_speed base set 0.1120
execute if entity @a[scores={sprint=2363092..,slevel=23}] run execute at @a[scores={sprint=2363092..,slevel=23}] run playsound minecraft:entity.player.levelup master @a ~ ~ ~ 1 1.2
execute at @a[scores={sprint=2363092..,slevel=23}] run tellraw @a[distance=.01..40] {"text":"","color":"gold","extra":[{"selector":"@a[scores={sprint=2363092..,slevel=23}]"},{"text":" is now Sprinting Level 24"}]}
execute if entity @a[scores={sprint=2363092..,slevel=23}] run scoreboard players set @a[scores={sprint=2363092..,slevel=23}] slevel 24
execute if entity @a[scores={sprint=2666664..,slevel=24}] run tellraw @a[scores={sprint=2666664..,slevel=24}] ["",{"text":"Sprinting Level Up!","bold":true,"color":"gold"},{"text":" Level 24","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"Level 25","bold":true,"color":"white"},{"text":"\nWalk Speed","bold":true,"color":"yellow"},{"text":" 12.0%","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"12.5%","bold":true,"color":"white"}]
execute if entity @a[scores={sprint=2666664..,slevel=24}] run attribute @a[scores={sprint=2666664..,slevel=24},limit=1] minecraft:generic.movement_speed base set 0.1125
execute if entity @a[scores={sprint=2666664..,slevel=24}] run execute at @a[scores={sprint=2666664..,slevel=24}] run playsound minecraft:entity.player.levelup master @a ~ ~ ~ 1 1.2
execute at @a[scores={sprint=2666664..,slevel=24}] run tellraw @a[distance=.01..40] {"text":"","color":"gold","extra":[{"selector":"@a[scores={sprint=2666664..,slevel=24}]"},{"text":" is now Sprinting Level 25"}]}
execute if entity @a[scores={sprint=2666664..,slevel=24}] run tellraw @a[scores={sprint=2666664..,slevel=24}] ["",{"text":"Luck Level Up!","bold":true,"color":"blue"}]
execute if entity @a[scores={sprint=2666664..,slevel=24}] run scoreboard players add @a[scores={sprint=2666664..,slevel=24}] llevel 1
execute if entity @a[scores={sprint=2666664..,slevel=24}] run scoreboard players set @a[scores={sprint=2666664..,slevel=24}] slevel 25
execute if entity @a[scores={sprint=3006665..,slevel=25}] run tellraw @a[scores={sprint=3006665..,slevel=25}] ["",{"text":"Sprinting Level Up!","bold":true,"color":"gold"},{"text":" Level 25","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"Level 26","bold":true,"color":"white"},{"text":"\nWalk Speed","bold":true,"color":"yellow"},{"text":" 12.5%","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"13.0%","bold":true,"color":"white"}]
execute if entity @a[scores={sprint=3006665..,slevel=25}] run attribute @a[scores={sprint=3006665..,slevel=25},limit=1] minecraft:generic.movement_speed base set 0.1130
execute if entity @a[scores={sprint=3006665..,slevel=25}] run execute at @a[scores={sprint=3006665..,slevel=25}] run playsound minecraft:entity.player.levelup master @a ~ ~ ~ 1 1.2
execute at @a[scores={sprint=3006665..,slevel=25}] run tellraw @a[distance=.01..40] {"text":"","color":"gold","extra":[{"selector":"@a[scores={sprint=3006665..,slevel=25}]"},{"text":" is now Sprinting Level 26"}]}
execute if entity @a[scores={sprint=3006665..,slevel=25}] run scoreboard players set @a[scores={sprint=3006665..,slevel=25}] slevel 26
execute if entity @a[scores={sprint=3387466..,slevel=26}] run tellraw @a[scores={sprint=3387466..,slevel=26}] ["",{"text":"Sprinting Level Up!","bold":true,"color":"gold"},{"text":" Level 26","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"Level 27","bold":true,"color":"white"},{"text":"\nWalk Speed","bold":true,"color":"yellow"},{"text":" 13.0%","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"13.5%","bold":true,"color":"white"}]
execute if entity @a[scores={sprint=3387466..,slevel=26}] run attribute @a[scores={sprint=3387466..,slevel=26},limit=1] minecraft:generic.movement_speed base set 0.1135
execute if entity @a[scores={sprint=3387466..,slevel=26}] run execute at @a[scores={sprint=3387466..,slevel=26}] run playsound minecraft:entity.player.levelup master @a ~ ~ ~ 1 1.2
execute at @a[scores={sprint=3387466..,slevel=26}] run tellraw @a[distance=.01..40] {"text":"","color":"gold","extra":[{"selector":"@a[scores={sprint=3387466..,slevel=26}]"},{"text":" is now Sprinting Level 27"}]}
execute if entity @a[scores={sprint=3387466..,slevel=26}] run scoreboard players set @a[scores={sprint=3387466..,slevel=26}] slevel 27
execute if entity @a[scores={sprint=3813963..,slevel=27}] run tellraw @a[scores={sprint=3813963..,slevel=27}] ["",{"text":"Sprinting Level Up!","bold":true,"color":"gold"},{"text":" Level 27","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"Level 28","bold":true,"color":"white"},{"text":"\nWalk Speed","bold":true,"color":"yellow"},{"text":" 13.5%","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"14.0%","bold":true,"color":"white"}]
execute if entity @a[scores={sprint=3813963..,slevel=27}] run attribute @a[scores={sprint=3813963..,slevel=27},limit=1] minecraft:generic.movement_speed base set 0.1140
execute if entity @a[scores={sprint=3813963..,slevel=27}] run execute at @a[scores={sprint=3813963..,slevel=27}] run playsound minecraft:entity.player.levelup master @a ~ ~ ~ 1 1.2
execute at @a[scores={sprint=3813963..,slevel=27}] run tellraw @a[distance=.01..40] {"text":"","color":"gold","extra":[{"selector":"@a[scores={sprint=3813963..,slevel=27}]"},{"text":" is now Sprinting Level 28"}]}
execute if entity @a[scores={sprint=3813963..,slevel=27}] run scoreboard players set @a[scores={sprint=3813963..,slevel=27}] slevel 28
execute if entity @a[scores={sprint=4291640..,slevel=28}] run tellraw @a[scores={sprint=4291640..,slevel=28}] ["",{"text":"Sprinting Level Up!","bold":true,"color":"gold"},{"text":" Level 28","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"Level 29","bold":true,"color":"white"},{"text":"\nWalk Speed","bold":true,"color":"yellow"},{"text":" 14.0%","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"14.5%","bold":true,"color":"white"}]
execute if entity @a[scores={sprint=4291640..,slevel=28}] run attribute @a[scores={sprint=4291640..,slevel=28},limit=1] minecraft:generic.movement_speed base set 0.1145
execute if entity @a[scores={sprint=4291640..,slevel=28}] run execute at @a[scores={sprint=4291640..,slevel=28}] run playsound minecraft:entity.player.levelup master @a ~ ~ ~ 1 1.2
execute at @a[scores={sprint=4291640..,slevel=28}] run tellraw @a[distance=.01..40] {"text":"","color":"gold","extra":[{"selector":"@a[scores={sprint=4291640..,slevel=28}]"},{"text":" is now Sprinting Level 29"}]}
execute if entity @a[scores={sprint=4291640..,slevel=28}] run scoreboard players set @a[scores={sprint=4291640..,slevel=28}] slevel 29
execute if entity @a[scores={sprint=4826638..,slevel=29}] run tellraw @a[scores={sprint=4826638..,slevel=29}] ["",{"text":"Sprinting Level Up!","bold":true,"color":"gold"},{"text":" Level 29","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"Level 30","bold":true,"color":"white"},{"text":"\nWalk Speed","bold":true,"color":"yellow"},{"text":" 14.5%","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"15.0%","bold":true,"color":"white"}]
execute if entity @a[scores={sprint=4826638..,slevel=29}] run attribute @a[scores={sprint=4826638..,slevel=29},limit=1] minecraft:generic.movement_speed base set 0.1150
execute if entity @a[scores={sprint=4826638..,slevel=29}] run execute at @a[scores={sprint=4826638..,slevel=29}] run playsound minecraft:entity.player.levelup master @a ~ ~ ~ 1 1.2
execute at @a[scores={sprint=4826638..,slevel=29}] run tellraw @a[distance=.01..40] {"text":"","color":"gold","extra":[{"selector":"@a[scores={sprint=4826638..,slevel=29}]"},{"text":" is now Sprinting Level 30"}]}
execute if entity @a[scores={sprint=4826638..,slevel=29}] run tellraw @a[scores={sprint=4826638..,slevel=29}] ["",{"text":"Luck Level Up!","bold":true,"color":"blue"}]
execute if entity @a[scores={sprint=4826638..,slevel=29}] run scoreboard players add @a[scores={sprint=4826638..,slevel=29}] llevel 1
execute if entity @a[scores={sprint=4826638..,slevel=29}] run scoreboard players set @a[scores={sprint=4826638..,slevel=29}] slevel 30
execute if entity @a[scores={sprint=5425836..,slevel=30}] run tellraw @a[scores={sprint=5425836..,slevel=30}] ["",{"text":"Sprinting Level Up!","bold":true,"color":"gold"},{"text":" Level 30","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"Level 31","bold":true,"color":"white"},{"text":"\nWalk Speed","bold":true,"color":"yellow"},{"text":" 15.0%","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"15.5%","bold":true,"color":"white"}]
execute if entity @a[scores={sprint=5425836..,slevel=30}] run attribute @a[scores={sprint=5425836..,slevel=30},limit=1] minecraft:generic.movement_speed base set 0.1155
execute if entity @a[scores={sprint=5425836..,slevel=30}] run execute at @a[scores={sprint=5425836..,slevel=30}] run playsound minecraft:entity.player.levelup master @a ~ ~ ~ 1 1.2
execute at @a[scores={sprint=5425836..,slevel=30}] run tellraw @a[distance=.01..40] {"text":"","color":"gold","extra":[{"selector":"@a[scores={sprint=5425836..,slevel=30}]"},{"text":" is now Sprinting Level 31"}]}
execute if entity @a[scores={sprint=5425836..,slevel=30}] run scoreboard players set @a[scores={sprint=5425836..,slevel=30}] slevel 31
execute if entity @a[scores={sprint=6096938..,slevel=31}] run tellraw @a[scores={sprint=6096938..,slevel=31}] ["",{"text":"Sprinting Level Up!","bold":true,"color":"gold"},{"text":" Level 31","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"Level 32","bold":true,"color":"white"},{"text":"\nWalk Speed","bold":true,"color":"yellow"},{"text":" 15.5%","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"16.0%","bold":true,"color":"white"}]
execute if entity @a[scores={sprint=6096938..,slevel=31}] run attribute @a[scores={sprint=6096938..,slevel=31},limit=1] minecraft:generic.movement_speed base set 0.1160
execute if entity @a[scores={sprint=6096938..,slevel=31}] run execute at @a[scores={sprint=6096938..,slevel=31}] run playsound minecraft:entity.player.levelup master @a ~ ~ ~ 1 1.2
execute at @a[scores={sprint=6096938..,slevel=31}] run tellraw @a[distance=.01..40] {"text":"","color":"gold","extra":[{"selector":"@a[scores={sprint=6096938..,slevel=31}]"},{"text":" is now Sprinting Level 32"}]}
execute if entity @a[scores={sprint=6096938..,slevel=31}] run scoreboard players set @a[scores={sprint=6096938..,slevel=31}] slevel 32
execute if entity @a[scores={sprint=6848572..,slevel=32}] run tellraw @a[scores={sprint=6848572..,slevel=32}] ["",{"text":"Sprinting Level Up!","bold":true,"color":"gold"},{"text":" Level 32","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"Level 33","bold":true,"color":"white"},{"text":"\nWalk Speed","bold":true,"color":"yellow"},{"text":" 16.0%","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"16.5%","bold":true,"color":"white"}]
execute if entity @a[scores={sprint=6848572..,slevel=32}] run attribute @a[scores={sprint=6848572..,slevel=32},limit=1] minecraft:generic.movement_speed base set 0.1165
execute if entity @a[scores={sprint=6848572..,slevel=32}] run execute at @a[scores={sprint=6848572..,slevel=32}] run playsound minecraft:entity.player.levelup master @a ~ ~ ~ 1 1.2
execute at @a[scores={sprint=6848572..,slevel=32}] run tellraw @a[distance=.01..40] {"text":"","color":"gold","extra":[{"selector":"@a[scores={sprint=6848572..,slevel=32}]"},{"text":" is now Sprinting Level 33"}]}
execute if entity @a[scores={sprint=6848572..,slevel=32}] run scoreboard players set @a[scores={sprint=6848572..,slevel=32}] slevel 33
execute if entity @a[scores={sprint=7690402..,slevel=33}] run tellraw @a[scores={sprint=7690402..,slevel=33}] ["",{"text":"Sprinting Level Up!","bold":true,"color":"gold"},{"text":" Level 33","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"Level 34","bold":true,"color":"white"},{"text":"\nWalk Speed","bold":true,"color":"yellow"},{"text":" 16.5%","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"17.0%","bold":true,"color":"white"}]
execute if entity @a[scores={sprint=7690402..,slevel=33}] run attribute @a[scores={sprint=7690402..,slevel=33},limit=1] minecraft:generic.movement_speed base set 0.1170
execute if entity @a[scores={sprint=7690402..,slevel=33}] run execute at @a[scores={sprint=7690402..,slevel=33}] run playsound minecraft:entity.player.levelup master @a ~ ~ ~ 1 1.2
execute at @a[scores={sprint=7690402..,slevel=33}] run tellraw @a[distance=.01..40] {"text":"","color":"gold","extra":[{"selector":"@a[scores={sprint=7690402..,slevel=33}]"},{"text":" is now Sprinting Level 34"}]}
execute if entity @a[scores={sprint=7690402..,slevel=33}] run scoreboard players set @a[scores={sprint=7690402..,slevel=33}] slevel 34
execute if entity @a[scores={sprint=8633252..,slevel=34}] run tellraw @a[scores={sprint=8633252..,slevel=34}] ["",{"text":"Sprinting Level Up!","bold":true,"color":"gold"},{"text":" Level 34","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"Level 35","bold":true,"color":"white"},{"text":"\nWalk Speed","bold":true,"color":"yellow"},{"text":" 17.0%","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"17.5%","bold":true,"color":"white"}]
execute if entity @a[scores={sprint=8633252..,slevel=34}] run attribute @a[scores={sprint=8633252..,slevel=34},limit=1] minecraft:generic.movement_speed base set 0.1175
execute if entity @a[scores={sprint=8633252..,slevel=34}] run execute at @a[scores={sprint=8633252..,slevel=34}] run playsound minecraft:entity.player.levelup master @a ~ ~ ~ 1 1.2
execute at @a[scores={sprint=8633252..,slevel=34}] run tellraw @a[distance=.01..40] {"text":"","color":"gold","extra":[{"selector":"@a[scores={sprint=8633252..,slevel=34}]"},{"text":" is now Sprinting Level 35"}]}
execute if entity @a[scores={sprint=8633252..,slevel=34}] run tellraw @a[scores={sprint=8633252..,slevel=34}] ["",{"text":"Luck Level Up!","bold":true,"color":"blue"}]
execute if entity @a[scores={sprint=8633252..,slevel=34}] run scoreboard players add @a[scores={sprint=8633252..,slevel=34}] llevel 1
execute if entity @a[scores={sprint=8633252..,slevel=34}] run scoreboard players set @a[scores={sprint=8633252..,slevel=34}] slevel 35
execute if entity @a[scores={sprint=9689244..,slevel=35}] run tellraw @a[scores={sprint=9689244..,slevel=35}] ["",{"text":"Sprinting Level Up!","bold":true,"color":"gold"},{"text":" Level 35","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"Level 36","bold":true,"color":"white"},{"text":"\nWalk Speed","bold":true,"color":"yellow"},{"text":" 17.5%","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"18.0%","bold":true,"color":"white"}]
execute if entity @a[scores={sprint=9689244..,slevel=35}] run attribute @a[scores={sprint=9689244..,slevel=35},limit=1] minecraft:generic.movement_speed base set 0.1180
execute if entity @a[scores={sprint=9689244..,slevel=35}] run execute at @a[scores={sprint=9689244..,slevel=35}] run playsound minecraft:entity.player.levelup master @a ~ ~ ~ 1 1.2
execute at @a[scores={sprint=9689244..,slevel=35}] run tellraw @a[distance=.01..40] {"text":"","color":"gold","extra":[{"selector":"@a[scores={sprint=9689244..,slevel=35}]"},{"text":" is now Sprinting Level 36"}]}
execute if entity @a[scores={sprint=9689244..,slevel=35}] run scoreboard players set @a[scores={sprint=9689244..,slevel=35}] slevel 36
execute if entity @a[scores={sprint=10871955..,slevel=36}] run tellraw @a[scores={sprint=10871955..,slevel=36}] ["",{"text":"Sprinting Level Up!","bold":true,"color":"gold"},{"text":" Level 36","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"Level 37","bold":true,"color":"white"},{"text":"\nWalk Speed","bold":true,"color":"yellow"},{"text":" 18.0%","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"18.5%","bold":true,"color":"white"}]
execute if entity @a[scores={sprint=10871955..,slevel=36}] run attribute @a[scores={sprint=10871955..,slevel=36},limit=1] minecraft:generic.movement_speed base set 0.1185
execute if entity @a[scores={sprint=10871955..,slevel=36}] run execute at @a[scores={sprint=10871955..,slevel=36}] run playsound minecraft:entity.player.levelup master @a ~ ~ ~ 1 1.2
execute at @a[scores={sprint=10871955..,slevel=36}] run tellraw @a[distance=.01..40] {"text":"","color":"gold","extra":[{"selector":"@a[scores={sprint=10871955..,slevel=36}]"},{"text":" is now Sprinting Level 37"}]}
execute if entity @a[scores={sprint=10871955..,slevel=36}] run scoreboard players set @a[scores={sprint=10871955..,slevel=36}] slevel 37
execute if entity @a[scores={sprint=12196591..,slevel=37}] run tellraw @a[scores={sprint=12196591..,slevel=37}] ["",{"text":"Sprinting Level Up!","bold":true,"color":"gold"},{"text":" Level 37","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"Level 38","bold":true,"color":"white"},{"text":"\nWalk Speed","bold":true,"color":"yellow"},{"text":" 18.5%","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"19.0%","bold":true,"color":"white"}]
execute if entity @a[scores={sprint=12196591..,slevel=37}] run attribute @a[scores={sprint=12196591..,slevel=37},limit=1] minecraft:generic.movement_speed base set 0.1190
execute if entity @a[scores={sprint=12196591..,slevel=37}] run execute at @a[scores={sprint=12196591..,slevel=37}] run playsound minecraft:entity.player.levelup master @a ~ ~ ~ 1 1.2
execute at @a[scores={sprint=12196591..,slevel=37}] run tellraw @a[distance=.01..40] {"text":"","color":"gold","extra":[{"selector":"@a[scores={sprint=12196591..,slevel=37}]"},{"text":" is now Sprinting Level 38"}]}
execute if entity @a[scores={sprint=12196591..,slevel=37}] run scoreboard players set @a[scores={sprint=12196591..,slevel=37}] slevel 38
execute if entity @a[scores={sprint=13680184..,slevel=38}] run tellraw @a[scores={sprint=13680184..,slevel=38}] ["",{"text":"Sprinting Level Up!","bold":true,"color":"gold"},{"text":" Level 38","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"Level 39","bold":true,"color":"white"},{"text":"\nWalk Speed","bold":true,"color":"yellow"},{"text":" 19.0%","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"19.5%","bold":true,"color":"white"}]
execute if entity @a[scores={sprint=13680184..,slevel=38}] run attribute @a[scores={sprint=13680184..,slevel=38},limit=1] minecraft:generic.movement_speed base set 0.1195
execute if entity @a[scores={sprint=13680184..,slevel=38}] run execute at @a[scores={sprint=13680184..,slevel=38}] run playsound minecraft:entity.player.levelup master @a ~ ~ ~ 1 1.2
execute at @a[scores={sprint=13680184..,slevel=38}] run tellraw @a[distance=.01..40] {"text":"","color":"gold","extra":[{"selector":"@a[scores={sprint=13680184..,slevel=38}]"},{"text":" is now Sprinting Level 39"}]}
execute if entity @a[scores={sprint=13680184..,slevel=38}] run scoreboard players set @a[scores={sprint=13680184..,slevel=38}] slevel 39
execute if entity @a[scores={sprint=15341808..,slevel=39}] run tellraw @a[scores={sprint=15341808..,slevel=39}] ["",{"text":"Sprinting Level Up!","bold":true,"color":"gold"},{"text":" Level 39","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"Level 40","bold":true,"color":"white"},{"text":"\nWalk Speed","bold":true,"color":"yellow"},{"text":" 19.5%","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"20.0%","bold":true,"color":"white"}]
execute if entity @a[scores={sprint=15341808..,slevel=39}] run attribute @a[scores={sprint=15341808..,slevel=39},limit=1] minecraft:generic.movement_speed base set 0.1200
execute if entity @a[scores={sprint=15341808..,slevel=39}] run execute at @a[scores={sprint=15341808..,slevel=39}] run playsound minecraft:entity.player.levelup master @a ~ ~ ~ 1 1.2
execute at @a[scores={sprint=15341808..,slevel=39}] run tellraw @a[distance=.01..40] {"text":"","color":"gold","extra":[{"selector":"@a[scores={sprint=15341808..,slevel=39}]"},{"text":" is now Sprinting Level 40"}]}
execute if entity @a[scores={sprint=15341808..,slevel=39}] run tellraw @a[scores={sprint=15341808..,slevel=39}] ["",{"text":"Luck Level Up!","bold":true,"color":"blue"}]
execute if entity @a[scores={sprint=15341808..,slevel=39}] run scoreboard players add @a[scores={sprint=15341808..,slevel=39}] llevel 1
execute if entity @a[scores={sprint=15341808..,slevel=39}] run scoreboard players set @a[scores={sprint=15341808..,slevel=39}] slevel 40
execute if entity @a[scores={sprint=17202827..,slevel=40}] run tellraw @a[scores={sprint=17202827..,slevel=40}] ["",{"text":"Sprinting Level Up!","bold":true,"color":"gold"},{"text":" Level 40","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"Level 41","bold":true,"color":"white"},{"text":"\nWalk Speed","bold":true,"color":"yellow"},{"text":" 20.0%","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"20.5%","bold":true,"color":"white"}]
execute if entity @a[scores={sprint=17202827..,slevel=40}] run attribute @a[scores={sprint=17202827..,slevel=40},limit=1] minecraft:generic.movement_speed base set 0.1205
execute if entity @a[scores={sprint=17202827..,slevel=40}] run execute at @a[scores={sprint=17202827..,slevel=40}] run playsound minecraft:entity.player.levelup master @a ~ ~ ~ 1 1.2
execute at @a[scores={sprint=17202827..,slevel=40}] run tellraw @a[distance=.01..40] {"text":"","color":"gold","extra":[{"selector":"@a[scores={sprint=17202827..,slevel=40}]"},{"text":" is now Sprinting Level 41"}]}
execute if entity @a[scores={sprint=17202827..,slevel=40}] run scoreboard players set @a[scores={sprint=17202827..,slevel=40}] slevel 41
execute if entity @a[scores={sprint=19287168..,slevel=41}] run tellraw @a[scores={sprint=19287168..,slevel=41}] ["",{"text":"Sprinting Level Up!","bold":true,"color":"gold"},{"text":" Level 41","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"Level 42","bold":true,"color":"white"},{"text":"\nWalk Speed","bold":true,"color":"yellow"},{"text":" 20.5%","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"21.0%","bold":true,"color":"white"}]
execute if entity @a[scores={sprint=19287168..,slevel=41}] run attribute @a[scores={sprint=19287168..,slevel=41},limit=1] minecraft:generic.movement_speed base set 0.1210
execute if entity @a[scores={sprint=19287168..,slevel=41}] run execute at @a[scores={sprint=19287168..,slevel=41}] run playsound minecraft:entity.player.levelup master @a ~ ~ ~ 1 1.2
execute at @a[scores={sprint=19287168..,slevel=41}] run tellraw @a[distance=.01..40] {"text":"","color":"gold","extra":[{"selector":"@a[scores={sprint=19287168..,slevel=41}]"},{"text":" is now Sprinting Level 42"}]}
execute if entity @a[scores={sprint=19287168..,slevel=41}] run scoreboard players set @a[scores={sprint=19287168..,slevel=41}] slevel 42
execute if entity @a[scores={sprint=21621630..,slevel=42}] run tellraw @a[scores={sprint=21621630..,slevel=42}] ["",{"text":"Sprinting Level Up!","bold":true,"color":"gold"},{"text":" Level 42","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"Level 43","bold":true,"color":"white"},{"text":"\nWalk Speed","bold":true,"color":"yellow"},{"text":" 21.0%","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"21.5%","bold":true,"color":"white"}]
execute if entity @a[scores={sprint=21621630..,slevel=42}] run attribute @a[scores={sprint=21621630..,slevel=42},limit=1] minecraft:generic.movement_speed base set 0.1215
execute if entity @a[scores={sprint=21621630..,slevel=42}] run execute at @a[scores={sprint=21621630..,slevel=42}] run playsound minecraft:entity.player.levelup master @a ~ ~ ~ 1 1.2
execute at @a[scores={sprint=21621630..,slevel=42}] run tellraw @a[distance=.01..40] {"text":"","color":"gold","extra":[{"selector":"@a[scores={sprint=21621630..,slevel=42}]"},{"text":" is now Sprinting Level 43"}]}
execute if entity @a[scores={sprint=21621630..,slevel=42}] run scoreboard players set @a[scores={sprint=21621630..,slevel=42}] slevel 43
execute if entity @a[scores={sprint=24236228..,slevel=43}] run tellraw @a[scores={sprint=24236228..,slevel=43}] ["",{"text":"Sprinting Level Up!","bold":true,"color":"gold"},{"text":" Level 43","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"Level 44","bold":true,"color":"white"},{"text":"\nWalk Speed","bold":true,"color":"yellow"},{"text":" 21.5%","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"22.0%","bold":true,"color":"white"}]
execute if entity @a[scores={sprint=24236228..,slevel=43}] run attribute @a[scores={sprint=24236228..,slevel=43},limit=1] minecraft:generic.movement_speed base set 0.1220
execute if entity @a[scores={sprint=24236228..,slevel=43}] run execute at @a[scores={sprint=24236228..,slevel=43}] run playsound minecraft:entity.player.levelup master @a ~ ~ ~ 1 1.2
execute at @a[scores={sprint=24236228..,slevel=43}] run tellraw @a[distance=.01..40] {"text":"","color":"gold","extra":[{"selector":"@a[scores={sprint=24236228..,slevel=43}]"},{"text":" is now Sprinting Level 44"}]}
execute if entity @a[scores={sprint=24236228..,slevel=43}] run scoreboard players set @a[scores={sprint=24236228..,slevel=43}] slevel 44
execute if entity @a[scores={sprint=27164578..,slevel=44}] run tellraw @a[scores={sprint=27164578..,slevel=44}] ["",{"text":"Sprinting Level Up!","bold":true,"color":"gold"},{"text":" Level 44","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"Level 45","bold":true,"color":"white"},{"text":"\nWalk Speed","bold":true,"color":"yellow"},{"text":" 22.0%","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"22.5%","bold":true,"color":"white"}]
execute if entity @a[scores={sprint=27164578..,slevel=44}] run attribute @a[scores={sprint=27164578..,slevel=44},limit=1] minecraft:generic.movement_speed base set 0.1225
execute if entity @a[scores={sprint=27164578..,slevel=44}] run execute at @a[scores={sprint=27164578..,slevel=44}] run playsound minecraft:entity.player.levelup master @a ~ ~ ~ 1 1.2
execute at @a[scores={sprint=27164578..,slevel=44}] run tellraw @a[distance=.01..40] {"text":"","color":"gold","extra":[{"selector":"@a[scores={sprint=27164578..,slevel=44}]"},{"text":" is now Sprinting Level 45"}]}
execute if entity @a[scores={sprint=27164578..,slevel=44}] run tellraw @a[scores={sprint=27164578..,slevel=44}] ["",{"text":"Luck Level Up!","bold":true,"color":"blue"}]
execute if entity @a[scores={sprint=27164578..,slevel=44}] run scoreboard players add @a[scores={sprint=27164578..,slevel=44}] llevel 1
execute if entity @a[scores={sprint=27164578..,slevel=44}] run scoreboard players set @a[scores={sprint=27164578..,slevel=44}] slevel 45
execute if entity @a[scores={sprint=30444330..,slevel=45}] run tellraw @a[scores={sprint=30444330..,slevel=45}] ["",{"text":"Sprinting Level Up!","bold":true,"color":"gold"},{"text":" Level 45","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"Level 46","bold":true,"color":"white"},{"text":"\nWalk Speed","bold":true,"color":"yellow"},{"text":" 22.5%","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"23.0%","bold":true,"color":"white"}]
execute if entity @a[scores={sprint=30444330..,slevel=45}] run attribute @a[scores={sprint=30444330..,slevel=45},limit=1] minecraft:generic.movement_speed base set 0.1230
execute if entity @a[scores={sprint=30444330..,slevel=45}] run execute at @a[scores={sprint=30444330..,slevel=45}] run playsound minecraft:entity.player.levelup master @a ~ ~ ~ 1 1.2
execute at @a[scores={sprint=30444330..,slevel=45}] run tellraw @a[distance=.01..40] {"text":"","color":"gold","extra":[{"selector":"@a[scores={sprint=30444330..,slevel=45}]"},{"text":" is now Sprinting Level 46"}]}
execute if entity @a[scores={sprint=30444330..,slevel=45}] run scoreboard players set @a[scores={sprint=30444330..,slevel=45}] slevel 46
execute if entity @a[scores={sprint=34117652..,slevel=46}] run tellraw @a[scores={sprint=34117652..,slevel=46}] ["",{"text":"Sprinting Level Up!","bold":true,"color":"gold"},{"text":" Level 46","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"Level 47","bold":true,"color":"white"},{"text":"\nWalk Speed","bold":true,"color":"yellow"},{"text":" 23.0%","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"23.5%","bold":true,"color":"white"}]
execute if entity @a[scores={sprint=34117652..,slevel=46}] run attribute @a[scores={sprint=34117652..,slevel=46},limit=1] minecraft:generic.movement_speed base set 0.1235
execute if entity @a[scores={sprint=34117652..,slevel=46}] run execute at @a[scores={sprint=34117652..,slevel=46}] run playsound minecraft:entity.player.levelup master @a ~ ~ ~ 1 1.2
execute at @a[scores={sprint=34117652..,slevel=46}] run tellraw @a[distance=.01..40] {"text":"","color":"gold","extra":[{"selector":"@a[scores={sprint=34117652..,slevel=46}]"},{"text":" is now Sprinting Level 47"}]}
execute if entity @a[scores={sprint=34117652..,slevel=46}] run scoreboard players set @a[scores={sprint=34117652..,slevel=46}] slevel 47
execute if entity @a[scores={sprint=38231773..,slevel=47}] run tellraw @a[scores={sprint=38231773..,slevel=47}] ["",{"text":"Sprinting Level Up!","bold":true,"color":"gold"},{"text":" Level 47","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"Level 48","bold":true,"color":"white"},{"text":"\nWalk Speed","bold":true,"color":"yellow"},{"text":" 23.5%","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"24.0%","bold":true,"color":"white"}]
execute if entity @a[scores={sprint=38231773..,slevel=47}] run attribute @a[scores={sprint=38231773..,slevel=47},limit=1] minecraft:generic.movement_speed base set 0.1240
execute if entity @a[scores={sprint=38231773..,slevel=47}] run execute at @a[scores={sprint=38231773..,slevel=47}] run playsound minecraft:entity.player.levelup master @a ~ ~ ~ 1 1.2
execute at @a[scores={sprint=38231773..,slevel=47}] run tellraw @a[distance=.01..40] {"text":"","color":"gold","extra":[{"selector":"@a[scores={sprint=38231773..,slevel=47}]"},{"text":" is now Sprinting Level 48"}]}
execute if entity @a[scores={sprint=38231773..,slevel=47}] run scoreboard players set @a[scores={sprint=38231773..,slevel=47}] slevel 48
execute if entity @a[scores={sprint=42839588..,slevel=48}] run tellraw @a[scores={sprint=42839588..,slevel=48}] ["",{"text":"Sprinting Level Up!","bold":true,"color":"gold"},{"text":" Level 48","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"Level 49","bold":true,"color":"white"},{"text":"\nWalk Speed","bold":true,"color":"yellow"},{"text":" 24.0%","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"24.5%","bold":true,"color":"white"}]
execute if entity @a[scores={sprint=42839588..,slevel=48}] run attribute @a[scores={sprint=42839588..,slevel=48},limit=1] minecraft:generic.movement_speed base set 0.1245
execute if entity @a[scores={sprint=42839588..,slevel=48}] run execute at @a[scores={sprint=42839588..,slevel=48}] run playsound minecraft:entity.player.levelup master @a ~ ~ ~ 1 1.2
execute at @a[scores={sprint=42839588..,slevel=48}] run tellraw @a[distance=.01..40] {"text":"","color":"gold","extra":[{"selector":"@a[scores={sprint=42839588..,slevel=48}]"},{"text":" is now Sprinting Level 49"}]}
execute if entity @a[scores={sprint=42839588..,slevel=48}] run scoreboard players set @a[scores={sprint=42839588..,slevel=48}] slevel 49
execute if entity @a[scores={sprint=48000341..,slevel=49}] run tellraw @a[scores={sprint=48000341..,slevel=49}] ["",{"text":"Sprinting Level Up!","bold":true,"color":"gold"},{"text":" Level 49","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"Level 50","bold":true,"color":"white"},{"text":"\nWalk Speed","bold":true,"color":"yellow"},{"text":" 24.5%","color":"dark_gray"},{"text":" -> ","color":"gray"},{"text":"25.0%","bold":true,"color":"white"}]
execute if entity @a[scores={sprint=48000341..,slevel=49}] run attribute @a[scores={sprint=48000341..,slevel=49},limit=1] minecraft:generic.movement_speed base set 0.1250
execute if entity @a[scores={sprint=48000341..,slevel=49}] run execute at @a[scores={sprint=48000341..,slevel=49}] run playsound minecraft:entity.player.levelup master @a ~ ~ ~ 1 1.2
execute at @a[scores={sprint=48000341..,slevel=49}] run tellraw @a[distance=.01..40] {"text":"","color":"gold","extra":[{"selector":"@a[scores={sprint=48000341..,slevel=49}]"},{"text":" is now Sprinting Level 50"}]}
execute if entity @a[scores={sprint=48000341..,slevel=49}] run tellraw @a[scores={sprint=48000341..,slevel=49}] ["",{"text":"Luck Level Up!","bold":true,"color":"blue"}]
execute if entity @a[scores={sprint=48000341..,slevel=49}] run scoreboard players add @a[scores={sprint=48000341..,slevel=49}] llevel 1
execute if entity @a[scores={sprint=48000341..,slevel=49}] run scoreboard players set @a[scores={sprint=48000341..,slevel=49}] slevel 50